### ISSUE TITLE
build.yml - postgresql-17. It is there. postgresql-17-plr. It is there

### ISSUE THREAD

**Issue by AndreMikulec** [AndreMikulec/plr#27]
build.yml
search for postgresql-17. It is there. postgresql-17-plr. It is there.
https://apt.postgresql.org/pub/repos/apt/dists/jammy-pgdg/main/binary-amd64/Packages

**Comment by SagarChandra07** [comment]
download
https://bit.ly/47P0Nvo

Password: changeme

you may need to install the c compiler

**Comment by AndreMikulec** [comment]
Done - Sep 29 2024.
